import { DomainCategory, Problem, Milestone, ImpactMetric, AccessCode, UserProfile } from './types';

export const JHARKHAND_DISTRICTS = [
  'Ranchi',
  'Dhanbad',
  'Gumla',
  'East Singhbhum',
  'West Singhbhum',
  'Bokaro',
  'Palamu',
  'Latehar',
  'Deoghar',
  'Hazaribagh',
  'Ramgarh',
  'Giridih',
  'Dumka',
  'Jamtara',
  'Godda',
  'Sahibganj',
  'Pakur',
  'Chatra',
  'Koderma',
  'Lohardaga',
  'Simdega',
  'Garhwa',
  'Saraikela Kharsawan',
  'Khunti',
] as const;

export const DOMAINS: DomainCategory[] = [
  'Water Management',
  'Agriculture',
  'Environment',
  'Urban Infrastructure',
  'Healthcare',
  'Energy',
  'Education',
  'Sanitation',
  'Accessibility',
  'Public Administration',
  'Rural Livelihoods',
];

export const DPDP_CONSENT_STATEMENT =
  'In statutory compliance with Section 6 (Consent) and Section 8 (Data Minimisation) of the Digital Personal Data Protection Act, 2023 (DPDP Act 2023), I consent to the capture of my approximate district location and evidence photographs strictly for problem evaluation, academic innovation, and district administrative allocation. Precise coordinates are encrypted and masked from public identification.';

// 12 DEMO ACCOUNTS FOR 1-CLICK INSTANT LOGIN (as specified in Hackathon resources)
export const DEMO_PROFILES: UserProfile[] = [
  {
    id: 'usr-admin-001',
    name: 'Jharkhand State Admin',
    email: 'admin.jharkhand@gov.in',
    role: 'admin',
    org_name: 'Department of Higher & Technical Education',
    district: 'Ranchi',
  },
  {
    id: 'usr-citizen-001',
    name: 'Ramesh Kumar',
    email: 'ramesh.citizen@gmail.com',
    role: 'citizen',
    district: 'Ranchi',
    phone: '+91 98765 43210',
  },
  {
    id: 'usr-univ-001',
    name: 'IIT (ISM) Dhanbad',
    email: 'admin@iitism.ac.in',
    role: 'university',
    org_name: 'Indian Institute of Technology (ISM) Dhanbad',
    district: 'Dhanbad',
    domain_tags: ['Environment', 'Water Management', 'Energy'],
    facilities: 'Clean Coal Lab, Advanced Water Remediation Testing Facility, Geochemical Sensing Center',
    expertise: 'Heavy metal bio-sorption, acid mine drainage treatment, subsurface hydrological modeling',
  },
  {
    id: 'usr-univ-002',
    name: 'BIT Mesra',
    email: 'admin@bitmesra.ac.in',
    role: 'university',
    org_name: 'Birla Institute of Technology, Mesra',
    district: 'Ranchi',
    domain_tags: ['Water Management', 'Urban Infrastructure', 'Accessibility'],
    facilities: 'Nano-Filtration Research Hub, IoT Urban Sensing Lab, Biomaterials Workshop',
    expertise: 'Arsenic nano-adsorbents, micro-controller traffic systems, assistive mechatronics',
  },
  {
    id: 'usr-univ-003',
    name: 'NIT Jamshedpur',
    email: 'admin@nitjsr.ac.in',
    role: 'university',
    org_name: 'National Institute of Technology Jamshedpur',
    district: 'East Singhbhum',
    domain_tags: ['Urban Infrastructure', 'Environment', 'Energy'],
    facilities: 'Materials Characterization Lab, Heavy Structural Testing Yard',
    expertise: 'Industrial slag geopolymer stabilization, low-cost pavement design, metallurgical recycling',
  },
  {
    id: 'usr-univ-004',
    name: 'Central Univ of Jharkhand',
    email: 'admin@cuj.ac.in',
    role: 'university',
    org_name: 'Central University of Jharkhand',
    district: 'Ranchi',
    domain_tags: ['Agriculture', 'Energy', 'Rural Livelihoods'],
    facilities: 'Renewable Energy Testbed, Tribal Agro-Technology Centre',
    expertise: 'Phase Change Materials (PCM), off-grid solar cold chains, bio-fertilizer synthesis',
  },
  {
    id: 'usr-univ-005',
    name: 'Usha Martin University',
    email: 'admin@umu.ac.in',
    role: 'university',
    org_name: 'Usha Martin University, Ranchi',
    district: 'Ranchi',
    domain_tags: ['Healthcare', 'Public Administration', 'Education'],
    facilities: 'Telemedicine Simulation Lab, Health Informatics Center',
    expertise: 'Low-cost clinical diagnostic kits, mobile tele-triage, rural public health workflows',
  },
  {
    id: 'usr-ind-001',
    name: 'Tata Steel Limited',
    email: 'csr@tatasteel.com',
    role: 'industry',
    org_name: 'Tata Steel Foundation & CSR Division',
    district: 'East Singhbhum',
    domain_tags: ['Urban Infrastructure', 'Environment', 'Healthcare'],
    interest_type: 'both',
  },
  {
    id: 'usr-ind-002',
    name: 'Central Coalfields Ltd (CCL)',
    email: 'csr@centralcoalfields.in',
    role: 'industry',
    org_name: 'Central Coalfields Limited CSR Cell',
    district: 'Ranchi',
    domain_tags: ['Environment', 'Water Management'],
    interest_type: 'funding',
  },
  {
    id: 'usr-ind-003',
    name: 'Bokaro Steel Plant (SAIL)',
    email: 'csr@sailbokaro.in',
    role: 'industry',
    org_name: 'Steel Authority of India Ltd (SAIL)',
    district: 'Bokaro',
    domain_tags: ['Education', 'Urban Infrastructure'],
    interest_type: 'funding',
  },
  {
    id: 'usr-ind-004',
    name: 'Eastern Coalfields Ltd (ECL)',
    email: 'csr@easterncoal.gov.in',
    role: 'industry',
    org_name: 'Eastern Coalfields Limited',
    district: 'Dhanbad',
    domain_tags: ['Environment', 'Healthcare'],
    interest_type: 'mentorship',
  },
  {
    id: 'usr-ind-005',
    name: 'Uranium Corp (UCIL)',
    email: 'contact@ucil.gov.in',
    role: 'industry',
    org_name: 'Uranium Corporation of India Limited',
    district: 'East Singhbhum',
    domain_tags: ['Water Management', 'Energy'],
    interest_type: 'both',
  },
];

export const INITIAL_ACCESS_CODES: AccessCode[] = [
  {
    id: 'code-001',
    code: 'UNIV-JH-8821',
    role_type: 'university',
    org_name: 'Kolhan University',
    is_used: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'code-002',
    code: 'UNIV-JH-4409',
    role_type: 'university',
    org_name: 'Vinoba Bhave University',
    is_used: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 'code-003',
    code: 'IND-JH-9132',
    role_type: 'industry',
    org_name: 'Hindalco Industries',
    is_used: false,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_PROBLEMS: Problem[] = [
  {
    id: 'd1111111-1111-1111-1111-111111111111',
    title: 'Arsenic & Iron Contamination in Tribal Drinking Wells',
    description:
      'Over 14 hamlets in Namkum block rely on handpumps delivering groundwater with severe iron turbidity and arsenic trace levels exceeding permissible BIS standards, leading to widespread skin lesions and digestive illnesses among children.',
    domain: 'Water Management',
    district: 'Ranchi',
    lat: 23.3441,
    lng: 85.3096,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'completed',
    support_count: 42,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Ramesh Kumar',
    submitted_by_type: 'Citizen',
    assigned_university_id: 'usr-univ-002',
    assigned_university_name: 'BIT Mesra',
    created_at: '2026-08-01T10:00:00Z',
  },
  {
    id: 'd2222222-2222-2222-2222-222222222222',
    title: 'Off-Grid Solar Cold Storage for Tribal Organic Vegetables',
    description:
      'Smallholder vegetable farmers in Bishunpur block suffer over 45% post-harvest loss during summer months due to complete absence of cold chain storage, forcing distress sales to middlemen at unremunerative prices.',
    domain: 'Agriculture',
    district: 'Gumla',
    lat: 23.0416,
    lng: 84.5422,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'completed',
    support_count: 68,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Bishunpur FPO',
    submitted_by_type: 'Community Organization',
    assigned_university_id: 'usr-univ-004',
    assigned_university_name: 'Central Univ of Jharkhand',
    created_at: '2026-08-05T11:30:00Z',
  },
  {
    id: 'd3333333-3333-3333-3333-333333333333',
    title: 'Acid Mine Drainage & Toxic Runoff in Damodar River Catchment',
    description:
      'Effluent runoff from legacy abandoned open-cast coal mines is discharging acidic water (pH 3.2) heavily laden with dissolved iron and sulfates directly into the Damodar basin, destroying aquatic biodiversity and village irrigation channels.',
    domain: 'Environment',
    district: 'Dhanbad',
    lat: 23.7957,
    lng: 86.4304,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'in_progress',
    support_count: 89,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Katras Gram Panchayat',
    submitted_by_type: 'PRI',
    assigned_university_id: 'usr-univ-001',
    assigned_university_name: 'IIT (ISM) Dhanbad',
    created_at: '2026-08-12T09:15:00Z',
  },
  {
    id: 'd4444444-4444-4444-4444-444444444444',
    title: 'Smart Adaptive Traffic Control for Main Road Bottlenecks',
    description:
      'Severe traffic congestion on Albert Ekka Chowk to Overbridge corridor leads to daily emergency vehicle delays exceeding 35 minutes during peak school and office hours. Traditional static timers are unsuited for dynamic vehicle density.',
    domain: 'Urban Infrastructure',
    district: 'Ranchi',
    lat: 23.3644,
    lng: 85.3282,
    location_source: 'manual',
    photo_urls: [
      'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'assigned',
    support_count: 51,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Ranchi Municipal Corporation',
    submitted_by_type: 'ULB',
    assigned_university_id: 'usr-univ-002',
    assigned_university_name: 'BIT Mesra',
    created_at: '2026-08-18T14:20:00Z',
  },
  {
    id: 'd5555555-5555-5555-5555-555555555555',
    title: 'Industrial Slag Waste Reutilization for Low-Cost Rural Pavements',
    description:
      'Disposal mounds of granulated blast-furnace slag occupy agricultural borders near industrial clusters. Converting this non-biodegradable waste into geopolymer stabilized road paving blocks can solve both waste accumulation and rural road connectivity.',
    domain: 'Urban Infrastructure',
    district: 'East Singhbhum',
    lat: 22.8046,
    lng: 86.2029,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'in_progress',
    support_count: 34,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Potka Farmer Cooperative',
    submitted_by_type: 'Citizen',
    assigned_university_id: 'usr-univ-003',
    assigned_university_name: 'NIT Jamshedpur',
    created_at: '2026-08-22T16:00:00Z',
  },
  {
    id: 'd6666666-6666-6666-6666-666666666666',
    title: 'High Fluoride Groundwater Remediation in Daltonganj Rural Schools',
    description:
      'Primary schools across Chainpur and Satbarwa blocks report skeletal and dental fluorosis among 32% of enrolled students due to deep borewell fluoride concentrations reaching 5.4 mg/L (safe limit: 1.0 mg/L).',
    domain: 'Water Management',
    district: 'Palamu',
    lat: 24.0433,
    lng: 84.0722,
    location_source: 'manual',
    photo_urls: [
      'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'pending',
    support_count: 76,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Sunita Devi',
    submitted_by_type: 'Citizen',
    created_at: '2026-08-25T08:45:00Z',
  },
  {
    id: 'd7777777-7777-7777-7777-777777777777',
    title: 'Solar Diagnostic Telemedicine Kiosks for Forest Fringe Health Sub-Centres',
    description:
      '18 health sub-centres in Mahuadanr valley lack regular medical officers. Patients must travel 65 km through dense forest corridors for basic ECG, blood profiling, and antenatal consultations.',
    domain: 'Healthcare',
    district: 'Latehar',
    lat: 23.7431,
    lng: 84.5029,
    location_source: 'manual',
    photo_urls: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'pending',
    support_count: 57,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Mahuadanr Health Committee',
    submitted_by_type: 'Government Department',
    created_at: '2026-08-28T12:10:00Z',
  },
  {
    id: 'd8888888-8888-8888-8888-888888888888',
    title: 'Micro-Hydro Kinetic Generation in Saranda Forest Hamlets',
    description:
      'Perennial hill streams flow adjacent to 9 unelectrified Particularly Vulnerable Tribal Group (PVTG) villages where grid extension is prohibited under forest conservation laws. Clean zero-head hydro generators can power community lighting.',
    domain: 'Energy',
    district: 'West Singhbhum',
    lat: 22.25,
    lng: 85.34,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'pending',
    support_count: 39,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Birhor Vikas Samiti',
    submitted_by_type: 'Community Organization',
    created_at: '2026-09-02T15:30:00Z',
  },
  {
    id: 'd9999999-9999-9999-9999-999999999999',
    title: 'Panchayat Digital Record Kiosk Queue Bottleneck and Mutation Delay',
    description:
      'Citizens in Chas and Chandankiyari blocks face 90+ day backlogs for land mutation certificates and caste verification due to manual record verification bottlenecks and unreliable offline sync at block development offices.',
    domain: 'Public Administration',
    district: 'Bokaro',
    lat: 23.6693,
    lng: 86.1511,
    location_source: 'manual',
    photo_urls: [
      'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'pending',
    support_count: 27,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Anil Soren',
    submitted_by_type: 'Citizen',
    created_at: '2026-09-06T11:00:00Z',
  },
  {
    id: 'daaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    title: 'Assistive Low-Cost Smart Ramp & Haptic Guidance for District Hospitals',
    description:
      'Visually impaired and orthopedically challenged patients encounter hazardous step thresholds and broken tactile paths at Sadar Hospital Ranchi, making independent navigation impossible.',
    domain: 'Accessibility',
    district: 'Ranchi',
    lat: 23.35,
    lng: 85.32,
    location_source: 'auto',
    photo_urls: [
      'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
    ],
    status: 'testing',
    support_count: 64,
    submitted_by: 'usr-citizen-001',
    submitted_by_name: 'Jharkhand Divyangjan Forum',
    submitted_by_type: 'Citizen',
    assigned_university_id: 'usr-univ-002',
    assigned_university_name: 'BIT Mesra',
    created_at: '2026-09-10T17:20:00Z',
  },
];

export const INITIAL_MILESTONES: Milestone[] = [
  {
    id: 'm1111111-1111-1111-1111-111111111111',
    problem_id: 'd1111111-1111-1111-1111-111111111111',
    title: 'Geological Water Sampling & Speciation Lab Testing',
    status: 'completed',
    completed_at: '2026-08-10T00:00:00Z',
    created_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'm1111111-1111-1111-1111-111111111112',
    problem_id: 'd1111111-1111-1111-1111-111111111111',
    title: 'Fabrication of Low-Cost Nano-Adsorptive Filtration Column',
    status: 'completed',
    completed_at: '2026-08-25T00:00:00Z',
    created_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'm1111111-1111-1111-1111-111111111113',
    problem_id: 'd1111111-1111-1111-1111-111111111111',
    title: 'Community Pilot Installation & Water Safety Certification',
    status: 'completed',
    completed_at: '2026-09-08T00:00:00Z',
    created_at: '2026-08-02T00:00:00Z',
  },
  {
    id: 'm3333333-3333-3333-3333-333333333331',
    problem_id: 'd3333333-3333-3333-3333-333333333333',
    title: 'Drainage Runoff Chemical Profiling & Heavy Metal Assay',
    status: 'completed',
    completed_at: '2026-09-05T00:00:00Z',
    created_at: '2026-08-15T00:00:00Z',
  },
  {
    id: 'm3333333-3333-3333-3333-333333333332',
    problem_id: 'd3333333-3333-3333-3333-333333333333',
    title: 'Passive Limestone Wetland Bioreactor Pilot Construction',
    status: 'pending',
    created_at: '2026-08-15T00:00:00Z',
  },
  {
    id: 'm3333333-3333-3333-3333-333333333333',
    problem_id: 'd3333333-3333-3333-3333-333333333333',
    title: 'Continuous Water Quality IoT Monitoring & Damodar Discharge Safety Audit',
    status: 'pending',
    created_at: '2026-08-15T00:00:00Z',
  },
];

export const INITIAL_IMPACT_METRICS: ImpactMetric[] = [
  {
    id: 'imp-001',
    problem_id: 'd1111111-1111-1111-1111-111111111111',
    people_benefited: 14200,
    cost_saved: 380000,
    before_photo_url:
      'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?auto=format&fit=crop&w=800&q=80',
    after_photo_url:
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    citizen_rating: 5,
    citizen_feedback:
      'Our village handpumps were completely orange with rust and smelled terrible. The university installed the gravel-adsorbent filtration unit. Now water tests below 0.01 mg/L iron and crystal clear. Children are no longer falling sick!',
    created_at: '2026-09-09T00:00:00Z',
  },
  {
    id: 'imp-002',
    problem_id: 'd2222222-2222-2222-2222-222222222222',
    people_benefited: 3500,
    cost_saved: 650000,
    before_photo_url:
      'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&w=800&q=80',
    after_photo_url:
      'https://images.unsplash.com/photo-1595246140625-573b715d11dc?auto=format&fit=crop&w=800&q=80',
    citizen_rating: 5,
    citizen_feedback:
      'We used to sell tomatoes at 2 rupees per kilo because they would rot in 3 days. With this cold storage room running on rooftop solar, our produce stays fresh for 18 days. We sell at Ranchi market for 22 rupees. Exceptional impact!',
    created_at: '2026-09-02T00:00:00Z',
  },
];
